### ISSUE TITLE
moveit_msgs and moveit2 are not compatible 

### ISSUE THREAD

**Issue by simk0024** [osrf/nexus#5]
the most recent [commit](https://github.com/ros-planning/moveit_msgs/commit/64b65e287e767e600e0240308c56aff1eb59a2fa) of moveit_msgs had removed ChangeControlDimensions.srv and ChangeDriftDimensions, which is not compatible with the moveit2 package version indicated in [thirdpart.repos](https://github.com/OpenSourceRobotics/nexus/blob/main/thirdparty.repos)

```
thirdparty/moveit/moveit_msgs:
    type: git
    url: https://github.com/ros-planning/moveit_msgs.git
    version: ros2
thirdparty/moveit/moveit2:
    type: git
    url: https://github.com/koonpeng/moveit2.git
    version: kp/scale_get_cartesian_path_humble
```
